[2025-09-13T08:53:26.217+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-13T08:53:26.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nasa_apod_postgress.load_data_to_postgresql scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-13T08:53:26.229+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nasa_apod_postgress.load_data_to_postgresql scheduled__2025-09-12T00:00:00+00:00 [queued]>
[2025-09-13T08:53:26.230+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-13T08:53:26.241+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data_to_postgresql> on 2025-09-12 00:00:00+00:00
[2025-09-13T08:53:26.244+0000] {standard_task_runner.py:63} INFO - Started process 94385 to run task
[2025-09-13T08:53:26.247+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'nasa_apod_postgress', 'load_data_to_postgresql', 'scheduled__2025-09-12T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etlpipeline.py', '--cfg-path', '/tmp/tmpd6jbw4h9']
[2025-09-13T08:53:26.248+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask load_data_to_postgresql
[2025-09-13T08:53:26.274+0000] {task_command.py:426} INFO - Running <TaskInstance: nasa_apod_postgress.load_data_to_postgresql scheduled__2025-09-12T00:00:00+00:00 [running]> on host codespaces-4a882f
[2025-09-13T08:53:26.316+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nasa_apod_postgress' AIRFLOW_CTX_TASK_ID='load_data_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2025-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-12T00:00:00+00:00'
[2025-09-13T08:53:26.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-13T08:53:26.317+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-13T08:53:26.317+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/automated-etl-with-airflow/.airflow/dags/etlpipeline.py", line 70, in load_data_to_postgresql
    postgres_hook = PostgreesHook(postgres_conn_id="my_postgres_connection")
                    ^^^^^^^^^^^^^
NameError: name 'PostgreesHook' is not defined. Did you mean: 'PostgresHook'?
[2025-09-13T08:53:26.321+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nasa_apod_postgress, task_id=load_data_to_postgresql, run_id=scheduled__2025-09-12T00:00:00+00:00, execution_date=20250912T000000, start_date=20250913T085326, end_date=20250913T085326
[2025-09-13T08:53:26.330+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task load_data_to_postgresql (name 'PostgreesHook' is not defined; 94385)
[2025-09-13T08:53:26.339+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-13T08:53:26.351+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-13T08:53:26.352+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
